### PR TITLE
Refactor and add some tests for lib/file.js.

### PR DESCRIPTION
**Pull request by pscollins**
This starts to address #20. Two tests are failing --- file.parse and
file.parseMarkdownFile --- which may be related to #24.

### CODE REVIEW

**Comment by pscollins** [comment]
Probably should have made this a separate branch, whoops. My git-fu is not strong.

As I said, my tests for the functionality related to parsing markdown are broken --- for the input "# Hello\n\nWorld!" I expect to see {title: "Hello", payload: "<p>World!</p>"} but instead I see the title "# Hello."

Also, on the input "# Hello\nWorld!" I expect to see {title: "Hello", payload: "<p>World!</p>"} but instead I see {title: ""# Hello\nWorld!", payload: ""}. I didn't include a testcase for that because I wasn't positive if my understanding of the behavior was quite right. But I thought that might explain #24, if there's another step somewhere that drops posts with empty payloads.

I didn't test the title stuff correctly until after starting to refactor so I'm not sure if that's a regression I introduced or if it was present in the original.

**Comment by hmngwy** [comment]
> Probably should have made this a separate branch, whoops. My git-fu is not strong.

Same. Our endeavors align anyway, this should be ok for now.

I'm wondering why the # stuck around, the markdown library wouldn't miss that. Trying right now and here's how it behaves:

```
> md.render('# Hello\n\nWorld!');
'<h1>Hello</h1>\n<p>World!</p>\n'
```

In this case the expected `title` should be Hello, the dom parser simply finds the first H1 and uses `.text()`.

I'm merging this, we can add a test for this and expect "Hello" for the `title` given the same input, and start fixing afterwards.

**Comment by hmngwy** [comment]
##### For the first failing test

Ok I think I found our problem here, two things. First given [tests/file.js#L14](https://github.com/hmngwy/weblog.sh/blob/2a6530db1b25f8963d9756626c449b2f9599263e/tests/file.js#L14), we are rendering "#Hello\n\nWorld!" as markdown, this won't become an H1 because the spec requires a space between the `#` and the first word. So we are getting:

```
> md.render('#Hello\n\nWorld!');
'<p>#Hello</p>\n<p>World!</p>\n'
```

Second, in [tests/file.js#L17](https://github.com/hmngwy/weblog.sh/blob/2a6530db1b25f8963d9756626c449b2f9599263e/tests/file.js#L17), if I'm not mistaken, simply needs to be '.md' instead of '.txt' so that it's processed as markdown.

##### For the second failing test

[tests/file.js#L56](https://github.com/hmngwy/weblog.sh/blob/2a6530db1b25f8963d9756626c449b2f9599263e/tests/file.js#L56) should be `parseMarkdownPayload` instead of `parseTextPayload`, taking cues from the describe line.

:)

**Comment by pscollins** [comment]
Whoops! I probably should have paid closer attention to my tests.

**Pull request merged**
